In [10]:
# ==========================================
# Imports
# ==========================================

import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np
import mlflow.xgboost
import mlflow
import mlflow.sklearn
import dagshub

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

In [2]:
from pathlib import Path
import pandas as pd

BASE_DIR = Path(r"C:\Users\LENOVO\dev-ops-2026\lab 3")

df = pd.read_csv(BASE_DIR / "BostonHousing.csv")

print(df.shape)
df.head()

(506, 14)

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2

In [3]:
# ==========================================
# Dataset Information
# ==========================================

print("Shape:", df.shape)

print("\nColumns:")
print(df.columns)

print("\nMissing Values:")
print(df.isnull().sum())

df.head()

Shape: (506, 14)

Columns:
Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')

Missing Values:
crim       0
zn         0
indus      0
chas       0
nox        0
rm         0
age        0
dis        0
rad        0
tax        0
ptratio    0
b          0
lstat      0
medv       0
dtype: int64

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2

In [4]:
# ==========================================
# Separate Features and Target
# ==========================================

X = df.drop("medv", axis=1)
y = df["medv"]

print("Feature Shape:", X.shape)
print("Target Shape :", y.shape)

Feature Shape: (506, 13)
Target Shape : (506,)

In [5]:
# ==========================================
# Train-Test Split
# ==========================================

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training Set:", X_train.shape)
print("Testing Set :", X_test.shape)

Training Set: (404, 13)
Testing Set : (102, 13)

In [6]:
# ==========================================
# Connect MLflow to DagsHub
# ==========================================

import dagshub
import mlflow

dagshub.init(
    repo_owner="yasi-tiwari25",
    repo_name="dev-ops-2026",
    mlflow=True
)

mlflow.set_experiment("Lab-3 Boston Housing Regression")

print("Connected to DagsHub successfully!")

                                       ❗❗❗ AUTHORIZATION REQUIRED ❗❗❗

Output()

Open the following link in your browser to authorize the client:
https://dagshub.com/login/oauth/authorize?state=0121551c-704e-4d36-bc52-daa2586de55b&client_id=32b60ba385aa7cecf24046d8195a71c07dd345d9657977863b52e7748e0f0f28&middleman_request_id=974fe020c30f2b9dd1454eb198f217643f4fb69478c56b5bf719a7b41dbe5987

Accessing as yasi-tiwari25

Repository dev-ops-2026 doesn't exist, creating it under current user.

Initialized MLflow to track repo "yasi-tiwari25/dev-ops-2026"

Repository yasi-tiwari25/dev-ops-2026 initialized!

2026/08/07 09:12:11 INFO mlflow.tracking.fluent: Experiment with name 'Lab-3 Boston Housing Regression' does not exist. Creating a new experiment.

Connected to DagsHub successfully!

In [7]:
# ==========================================
# Linear Regression
# ==========================================

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import mlflow

model = LinearRegression()

with mlflow.start_run(run_name="Linear Regression"):

    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)

    mae = mean_absolute_error(y_test, y_pred)
    rmse = mean_squared_error(y_test, y_pred) ** 0.5
    r2 = r2_score(y_test, y_pred)

    mlflow.log_param("Model", "Linear Regression")

    mlflow.log_metric("MAE", mae)
    mlflow.log_metric("RMSE", rmse)
    mlflow.log_metric("R2", r2)

    mlflow.sklearn.log_model(model, "LinearRegressionModel")

print("MAE :", mae)
print("RMSE:", rmse)
print("R2  :", r2)

2026/08/07 09:12:42 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

🏃 View run Linear Regression at: https://dagshub.com/yasi-tiwari25/dev-ops-2026.mlflow/#/experiments/0/runs/c5ac484ad3944c2a8c6a56828fe2a658
🧪 View experiment at: https://dagshub.com/yasi-tiwari25/dev-ops-2026.mlflow/#/experiments/0
MAE : 3.1890919658878416
RMSE: 4.928602182665339
R2  : 0.6687594935356317

In [8]:
# ==========================================
# Random Forest Regression
# ==========================================

from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

with mlflow.start_run(run_name="Random Forest"):

    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)

    mae = mean_absolute_error(y_test, y_pred)
    rmse = mean_squared_error(y_test, y_pred) ** 0.5
    r2 = r2_score(y_test, y_pred)

    mlflow.log_param("Model", "Random Forest")

    mlflow.log_param("n_estimators", 100)

    mlflow.log_metric("MAE", mae)
    mlflow.log_metric("RMSE", rmse)
    mlflow.log_metric("R2", r2)

    mlflow.sklearn.log_model(model, "RandomForestModel")

print("MAE :", mae)
print("RMSE:", rmse)
print("R2  :", r2)

2026/08/07 09:16:37 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

🏃 View run Random Forest at: https://dagshub.com/yasi-tiwari25/dev-ops-2026.mlflow/#/experiments/0/runs/a73655c442be413ea3f4696473bb11ee
🧪 View experiment at: https://dagshub.com/yasi-tiwari25/dev-ops-2026.mlflow/#/experiments/0
MAE : 2.0395392156862746
RMSE: 2.8109631609391226
R2  : 0.8922527442109116

In [ ]:
# ==========================================
# XGBoost Regression
# ==========================================

from xgboost import XGBRegressor

model = XGBRegressor(
    n_estimators=100,
    learning_rate=0.1,
    random_state=42
)

with mlflow.start_run(run_name="XGBoost"):

    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)

    mae = mean_absolute_error(y_test, y_pred)
    rmse = mean_squared_error(y_test, y_pred) ** 0.5
    r2 = r2_score(y_test, y_pred)

    mlflow.log_param("Model", "XGBoost")

    mlflow.log_param("n_estimators", 100)
    mlflow.log_param("learning_rate", 0.1)

    mlflow.log_metric("MAE", mae)
    mlflow.log_metric("RMSE", rmse)
    mlflow.log_metric("R2", r2)
    mlflow.xgboost.log_model(model, "XGBoostModel")
print("MAE :", mae)
print("RMSE:", rmse)
print("R2  :", r2)

2026/08/07 09:18:09 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

🏃 View run XGBoost at: https://dagshub.com/yasi-tiwari25/dev-ops-2026.mlflow/#/experiments/0/runs/d2e69965ca9e4d82a5fcd0deffc8a758
🧪 View experiment at: https://dagshub.com/yasi-tiwari25/dev-ops-2026.mlflow/#/experiments/0

MlflowException: The saved sklearn model references untrusted types. If you are sure loading these types is safe, set the 'skops_trusted_types' parameter when calling 'log_model' or 'save_model' to the list of trusted types. Root error: Untrusted types found in the file: ['xgboost.core.Booster', 'xgboost.sklearn.XGBRegressor'].